name: Process that runs puppeteer and then jest attaches to the existing browser

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Testful Test
    steps:
      - uses: actions/checkout@v1
      - name: Install things for ubuntu
        run: apt-get update && apt-get install -yq libgconf-2-4 && apt-get install -y wget gnupg xvfb dbus-x11 --no-install-recommends && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && apt-get update && apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf --no-install-recommends && rm -rf /var/lib/apt/lists/*
      - name: npm install and test
        run:
          echo "@@@ Begin";
          npm i;
          npm run runner & sleep 10;
          npm run test:integration;
          echo "@@@ End";
        env:
          CI: true